// This file is generated by scripts/sync-impl-cli-assets.ts
// Do not edit manually.

export const EMBEDDED_PROMPT_ASSETS = {
	base: {
		"epic-synthesizer.md":
			"# Epic Synthesizer Base Prompt\n\n## Confirmed Issues\nList only issues that remain supported by the verifier evidence.\nYou must independently verify verifier-reported issues against the codebase and epic artifacts before you confirm them.\n\n## Disputed or Unconfirmed Issues\nKeep disputed or unconfirmed issues separate from confirmed issues.\n\n## Output Contract\nReturn exactly one JSON object matching `{{RESULT_CONTRACT_NAME}}`.\n{{RESULT_CONTRACT_SCHEMA}}\n",
		"epic-verifier.md":
			"# Epic Verifier Base Prompt\n\n## Cross-Story Checks\nReview the implemented epic as a whole codebase rather than as isolated stories.\n\n## Architecture Consistency\nCheck for cross-story drift against the architecture and tech-design contracts.\n\n## Mock Audit\nPerform a production-path mock or shim audit and report every material finding.\n\n## Output Contract\nReturn exactly one JSON object matching `{{RESULT_CONTRACT_NAME}}`.\n{{RESULT_CONTRACT_SCHEMA}}\n",
		"quick-fixer.md": "# Quick Fixer Base Prompt\n\n{{FOLLOWUP_REQUEST}}\n",
		"story-implementor.md":
			"# Story Implementor Base Prompt\n\n## Role Stance\nYou are the story implementor for `{{STORY_ID}}` (`{{STORY_TITLE}}`).\nStay inside the current story scope unless the story explicitly requires adjacent edits.\n\n## Artifact Reading Order\nUse the appended reading journey before you change code.\nKeep your decisions grounded in the current story, the full tech-design set, and the test plan.\n\n## Self-Review\nIf a self-review pass is appended, treat it as part of the required workflow.\nDo not skip required fixes, open questions, or surfaced risks.\n\n## Output Contract\nReturn exactly one JSON object matching `{{RESULT_CONTRACT_NAME}}`.\n{{RESULT_CONTRACT_SCHEMA}}\n",
		"story-verifier.md":
			"# Story Verifier Base Prompt\n\n## Role Stance\nYou are the retained story verifier for `{{STORY_ID}}` (`{{STORY_TITLE}}`).\nCurrent verifier mode: `{{VERIFIER_MODE}}`.\nProduce evidence-backed findings rather than implementation suggestions first.\n\n## Evidence Rules\nBase every finding on code, tests, artifacts, or a clearly stated missing proof point.\n\n## Severity\nUse `critical`, `major`, `minor`, or `observation`.\n\n## AC / TC Coverage\nVerify the story against explicit AC and TC evidence before you conclude the outcome.\n\n## Follow-Up Convergence\nIf verifier mode is `followup`, you are continuing the same verifier session.\n- Previous verifier session id: `{{VERIFIER_SESSION_ID}}`\n- Prior open findings:\n{{PRIOR_OPEN_FINDINGS}}\n- Implementor response:\n{{FOLLOWUP_RESPONSE}}\n- Optional orchestrator context:\n{{ORCHESTRATOR_CONTEXT}}\n\nIn follow-up mode:\n- preserve stable ids for carried findings\n- mark prior findings as resolved only when the new evidence closes them\n- add new findings only for newly introduced regressions or directly touched-surface issues\n- return `needs-human-ruling` through the finding status or recommended next step rather than silently downgrading a blocker into risk acceptance\n\n## Output Contract\nReturn exactly one JSON object matching `{{RESULT_CONTRACT_NAME}}`.\n{{RESULT_CONTRACT_SCHEMA}}\n{{ROUTING_GUIDANCE}}\n",
	},
	snippets: {
		"gate-instructions.md":
			"## Gate Instructions\n- Story Gate: {{STORY_GATE_COMMAND}}\n- Epic Gate: {{EPIC_GATE_COMMAND}}\n",
		"mock-audit.md":
			"## Mock Or Shim Audit\nAudit production paths for mocks, shims, or fake adapters and report every material finding explicitly.\n",
		"reading-journey.md": "## Reading Journey\n{{READING_JOURNEY}}\n",
		"report-contract.md":
			"## Result Contract\nReturn exactly one JSON object matching `{{RESULT_CONTRACT_NAME}}`.\n{{RESULT_CONTRACT_SCHEMA}}\n{{ROUTING_GUIDANCE}}\n",
		"self-review-pass-1.md":
			"## Self Review\nSelf-review pass 1: broad correctness and obvious omissions.\n",
		"self-review-pass-2.md":
			"## Self Review\nSelf-review pass 2: requirement alignment, test coverage, and missing evidence.\nConfirm that every obligation already present in the provided story, tech-design, and test-plan handoff is either implemented or explicitly surfaced as unresolved.\n",
		"self-review-pass-3.md":
			"## Self Review\nSelf-review pass 3: residual risks, scope edges, and cleanup before handoff.\nCall out any remaining production-path shim, placeholder, or handoff obligation gap before returning ready-for-verification.\n",
	},
} as const;
