import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname;
const PROMPTS_ROOT = join(ROOT, "src", "prompts");
const SKILLS_ROOT = join(ROOT, "src", "skills");
const OUTPUT_PATH = join(ROOT, "src", "core", "embedded-assets.generated.ts");

async function readMarkdownDirectory(
	dir: string,
): Promise<Record<string, string>> {
	const entries = await readdir(dir, { withFileTypes: true });
	const files = await Promise.all(
		entries
			.filter((entry) => entry.isFile() && entry.name.endsWith(".md"))
			.sort((left, right) => left.name.localeCompare(right.name))
			.map(async (entry) => {
				const path = join(dir, entry.name);
				return [entry.name, await readFile(path, "utf8")] as const;
			}),
	);
	return Object.fromEntries(files);
}

async function collectSkillFiles(
	skillDir: string,
): Promise<Record<string, string>> {
	const files: Record<string, string> = {};

	async function visit(dir: string): Promise<void> {
		const entries = await readdir(dir, { withFileTypes: true });
		for (const entry of entries.sort((left, right) =>
			left.name.localeCompare(right.name),
		)) {
			const path = join(dir, entry.name);
			if (entry.isDirectory()) {
				await visit(path);
				continue;
			}
			if (!entry.isFile() || !entry.name.endsWith(".md")) {
				continue;
			}
			files[relative(skillDir, path).split("\\").join("/")] = await readFile(
				path,
				"utf8",
			);
		}
	}

	await visit(skillDir);
	return files;
}

async function readSkills(): Promise<Record<string, Record<string, string>>> {
	const entries = await readdir(SKILLS_ROOT, { withFileTypes: true });
	const skills = await Promise.all(
		entries
			.filter((entry) => entry.isDirectory())
			.sort((left, right) => left.name.localeCompare(right.name))
			.map(async (entry) => {
				return [
					entry.name,
					await collectSkillFiles(join(SKILLS_ROOT, entry.name)),
				] as const;
			}),
	);
	return Object.fromEntries(skills);
}

function renderConst(name: string, value: unknown): string {
	return `export const ${name} = ${JSON.stringify(value, null, "\t")} as const;\n`;
}

async function main(): Promise<void> {
	const embeddedPromptAssets = {
		base: await readMarkdownDirectory(join(PROMPTS_ROOT, "base")),
		snippets: await readMarkdownDirectory(join(PROMPTS_ROOT, "snippets")),
	};
	const embeddedSkillAssets = await readSkills();

	await writeFile(
		OUTPUT_PATH,
		[
			"// This file is generated by scripts/sync-impl-cli-assets.ts",
			"// Do not edit manually.",
			"// biome-ignore-all format: generated asset payload",
			"",
			renderConst("EMBEDDED_PROMPT_ASSETS", embeddedPromptAssets),
			renderConst("EMBEDDED_SKILL_ASSETS", embeddedSkillAssets),
		].join("\n"),
	);
}

await main();
